# Generated by Django 4.2.4 on 2023-11-08 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Toll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_status', models.PositiveSmallIntegerField(choices=[(0, 'Declined'), (1, 'Processing'), (2, 'Completed')], default=0)),
                ('toll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toll.toll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
