# Generated by Django 4.2.4 on 2023-11-08 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vehicle_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.vehicle'),
        ),
    ]
