# Generated by Django 4.2.4 on 2023-11-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toll',
            name='toll_charge_per_km',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
