# Generated by Django 4.2.4 on 2023-08-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tolls',
            fields=[
                ('toll_id', models.IntegerField(primary_key=True, serialize=False)),
                ('toll_name', models.CharField(max_length=30)),
                ('toll_location', models.CharField(max_length=30)),
                ('toll_price_collected', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('toll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gantry.tolls')),
            ],
        ),
    ]
