# Generated by Django 4.2.4 on 2023-09-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gantry', '0004_alter_transaction_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tolls',
            new_name='Toll',
        ),
    ]
