# Generated by Django 4.2.4 on 2023-11-05 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('addhar_number', models.CharField(max_length=12, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('account_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=10)),
                ('vehicle_model', models.CharField(max_length=10)),
                ('vehicle_distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
