# Generated by Django 3.2.19 on 2023-11-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='addhar_number',
            new_name='aadhar_number',
        ),
    ]
