# Generated by Django 4.2.4 on 2023-09-19 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gantry', '0005_rename_tolls_toll'),
        ('User', '0002_remove_profile_email_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
    ]
